name: weather_japan
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0-265.0.dev <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {http: ^0.13.4, path: ^1.8.1, synchronized: ^3.0.0+2, topojson: ^0.3.0}
