name: weather_japan
description: A weather forecast package inside Japan.
version: 0.3.0
homepage: https://github.com/espresso3389/weather_japan

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
dependencies:
  http: ^1.0.0
  path: ^1.8.1
  synchronized: ^3.0.0+2
  topojson: ^0.3.0

